/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExportRearrangerDialog.java
 *
 * Created on 06-nov-2010, 19:17:42
 */

package net.ajaest.jdk.gui.dialogs;

import javax.swing.ImageIcon;
import javax.swing.JTable;

import net.ajaest.jdk.core.main.Messages;
import net.ajaest.jdk.core.winHandlers.ExportRearrangerWH;

/**
 *
 * @author ajaest10
 */
public class ExportRearrangerDialog extends javax.swing.JDialog {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6296069649721877412L;
	private ExportRearrangerWH eradwh;

    /** Creates new form ExportRearrangerDialog */
    public ExportRearrangerDialog(java.awt.Frame parent, boolean modal,ExportRearrangerWH eradwh) {
        super(parent, modal);
        this.eradwh = eradwh;
		eradwh.setExportRearranger(this);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AcceptButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        OrderButtonsPanel = new javax.swing.JPanel();
        ImageIcon topIcon = new ImageIcon(this.getClass().getResource("/images/go-top.png"));
        GoTopButton = new javax.swing.JButton(topIcon);
        ImageIcon upIcon = new ImageIcon(this.getClass().getResource("/images/go-up.png"));
        GoUpButton = new javax.swing.JButton(upIcon);
        ImageIcon downIcon = new ImageIcon(this.getClass().getResource("/images/go-down.png"));
        GoDownButton = new javax.swing.JButton(downIcon);
        ImageIcon bottomIcon = new ImageIcon(this.getClass().getResource("/images/go-bottom.png"));
        GoBottomButton = new javax.swing.JButton(bottomIcon);
        KanjiRearrangeScrollPane = new javax.swing.JScrollPane();
        KanjiRearrangeTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(eradwh.getMessage(Messages.WINEXPORTREARRANGER_name));
        setLocationByPlatform(true);

        AcceptButton.setText(eradwh.getMessage(Messages.WINEXPORTREARRANGER_acceptButton));
        AcceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptButtonActionPerformed(evt);
            }
        });

        CancelButton.setText(eradwh.getMessage(Messages.WINEXPORTREARRANGER_cancelButton));
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        GoTopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoTopButtonActionPerformed(evt);
            }
        });

        GoUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoUpButtonActionPerformed(evt);
            }
        });

        GoDownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoDownButtonActionPerformed(evt);
            }
        });

        GoBottomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBottomButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OrderButtonsPanelLayout = new javax.swing.GroupLayout(OrderButtonsPanel);
        OrderButtonsPanel.setLayout(OrderButtonsPanelLayout);
        OrderButtonsPanelLayout.setHorizontalGroup(
            OrderButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GoTopButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
            .addComponent(GoBottomButton, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
            .addComponent(GoUpButton, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
            .addComponent(GoDownButton, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );
        OrderButtonsPanelLayout.setVerticalGroup(
            OrderButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderButtonsPanelLayout.createSequentialGroup()
                .addComponent(GoTopButton)
                .addGap(18, 18, 18)
                .addComponent(GoUpButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GoDownButton)
                .addGap(18, 18, 18)
                .addComponent(GoBottomButton))
        );

        KanjiRearrangeTable.setFont(eradwh.getUnicodeFont());
        KanjiRearrangeTable.setModel(eradwh.getRearrangeTableModel());
        KanjiRearrangeScrollPane.setViewportView(KanjiRearrangeTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(KanjiRearrangeScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(OrderButtonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AcceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OrderButtonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KanjiRearrangeScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelButton)
                    .addComponent(AcceptButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // getters

    public JTable getKanjiRearrangeTable(){
        return KanjiRearrangeTable;
    }

    // Actions performed

    private void GoTopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoTopButtonActionPerformed
        eradwh.goTopButtonPressed();
    }//GEN-LAST:event_GoTopButtonActionPerformed

    private void GoUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoUpButtonActionPerformed
        eradwh.goUpButtonPressed();
    }//GEN-LAST:event_GoUpButtonActionPerformed

    private void GoDownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoDownButtonActionPerformed
        eradwh.goDownButtonPressed();
    }//GEN-LAST:event_GoDownButtonActionPerformed

    private void GoBottomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBottomButtonActionPerformed
        eradwh.goBottomButtonPressed();
    }//GEN-LAST:event_GoBottomButtonActionPerformed

    private void AcceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptButtonActionPerformed
        eradwh.acceptButtonPressed();
    }//GEN-LAST:event_AcceptButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        eradwh.cancelButtonPressed();
    }//GEN-LAST:event_CancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton GoBottomButton;
    private javax.swing.JButton GoDownButton;
    private javax.swing.JButton GoTopButton;
    private javax.swing.JButton GoUpButton;
    private javax.swing.JScrollPane KanjiRearrangeScrollPane;
    private javax.swing.JTable KanjiRearrangeTable;
    private javax.swing.JPanel OrderButtonsPanel;
    // End of variables declaration//GEN-END:variables

}
